# Generated by Django 4.2.3 on 2023-07-25 16:41

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('D:/projects/django-web-store/django_web_store/media')),
        ),
    ]
