# Generated by Django 4.2.3 on 2023-07-25 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Category')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='childs', to='catalog_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Good')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods', to='catalog_app.category')),
            ],
        ),
    ]
