# Generated by Django 4.2.3 on 2023-07-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(db_index=True, default='', max_length=11, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='good',
            name='code',
            field=models.CharField(db_index=True, default='', max_length=11, verbose_name='code'),
        ),
    ]
